# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.m_pesa_stk_push_response_data import MPesaStkPushResponseData

class TestMPesaStkPushResponseData(unittest.TestCase):
    """MPesaStkPushResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MPesaStkPushResponseData:
        """Test MPesaStkPushResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MPesaStkPushResponseData`
        """
        model = MPesaStkPushResponseData()
        if include_optional:
            return MPesaStkPushResponseData(
                amount = 2.0,
                charge = 1.0,
                payment_reference = 'MKQR28922980073',
                invoice_number = 'INVDBU',
                order_reference = 'OR28922980077',
                amount_debited = 2.0
            )
        else:
            return MPesaStkPushResponseData(
        )
        """

    def testMPesaStkPushResponseData(self):
        """Test MPesaStkPushResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
