# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.m_pesa_stk_push_response import MPesaStkPushResponse

class TestMPesaStkPushResponse(unittest.TestCase):
    """MPesaStkPushResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MPesaStkPushResponse:
        """Test MPesaStkPushResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MPesaStkPushResponse`
        """
        model = MPesaStkPushResponse()
        if include_optional:
            return MPesaStkPushResponse(
                status = True,
                code = '0',
                message = 'Success. Request accepted for processing',
                data = jenga_client.models.m_pesa_stk_push_response_data.MPesaStkPushResponse_data(
                    amount = 2.0, 
                    charge = 1.0, 
                    payment_reference = 'MKQR28922980073', 
                    invoice_number = 'INVDBU', 
                    order_reference = 'OR28922980077', 
                    amount_debited = 2.0, )
            )
        else:
            return MPesaStkPushResponse(
        )
        """

    def testMPesaStkPushResponse(self):
        """Test MPesaStkPushResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
