# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.m_pesa_transaction_status import MPesaTransactionStatus

class TestMPesaTransactionStatus(unittest.TestCase):
    """MPesaTransactionStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MPesaTransactionStatus:
        """Test MPesaTransactionStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MPesaTransactionStatus`
        """
        model = MPesaTransactionStatus()
        if include_optional:
            return MPesaTransactionStatus(
                status = True,
                data = jenga_client.models.m_pesa_transaction_status_data.MPesaTransactionStatus_data(
                    order = jenga_client.models.m_pesa_transaction_status_data_order.MPesaTransactionStatus_data_order(
                        order_reference = 'REF123456', 
                        status = 'SUCCESS', 
                        amount = 1000.0, 
                        currency = 'KES', ), )
            )
        else:
            return MPesaTransactionStatus(
        )
        """

    def testMPesaTransactionStatus(self):
        """Test MPesaTransactionStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
