# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class MPesaStkPushResponseData(BaseModel):
    """
    MPesaStkPushResponseData
    """ # noqa: E501
    amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Transaction amount")
    charge: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Service charge")
    payment_reference: Optional[StrictStr] = Field(default=None, description="Payment reference", alias="paymentReference")
    invoice_number: Optional[StrictStr] = Field(default=None, description="Invoice number", alias="invoiceNumber")
    order_reference: Optional[StrictStr] = Field(default=None, description="Order reference", alias="orderReference")
    amount_debited: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Amount debited", alias="amountDebited")
    __properties: ClassVar[List[str]] = ["amount", "charge", "paymentReference", "invoiceNumber", "orderReference", "amountDebited"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MPesaStkPushResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MPesaStkPushResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amount": obj.get("amount"),
            "charge": obj.get("charge"),
            "paymentReference": obj.get("paymentReference"),
            "invoiceNumber": obj.get("invoiceNumber"),
            "orderReference": obj.get("orderReference"),
            "amountDebited": obj.get("amountDebited")
        })
        return _obj


